let items = [
    {   id: 0,
        name: 'Overprint Small Box',
        img: '/t-shirt.png',
        description: 'All cotton jersey crewneck with knockout printed logo at chest.',
        price: 88,
    },
    {   id: 1,
        name: 'Intarsia Label',
        img: '/t-shirt2.png',
        description: 'All cotton jersey crewneck with intarsia knit logo at chest',
        price: 88,
    },
    {   id: 2,
        name: 'Satchidananda Tee',
        img: '/t-shirt3.png',
        description: 'All cotton classic Supreme t-shirt with printed graphic on front.',
        price: 54,
    },
    {   id: 3,
        name: 'Dutch Sunglasses',
        img: '/dutch.png',
        description: 'Olive. Injection molded frames with anti-reflective lenses.',
        price: 178,
    },
    {   id: 4,
        name: 'Supreme®/Tetris®',
        img: '/tetris.png',
        description: 'Olive. Injection molded frames with anti-reflective lenses.',
        price: 34,
    },
    {   id: 5,
        name: 'Socks (4 Pack)',
        img: '/socks.png',
        description: 'Cotton blend Hanes cushion comfort socks.',
        price: 26,
    },
]

export {items}